---

name: Lint

on:
  pull_request:
    paths:
      - '**.jpg'
      # - '**.png'
      # - '**.webp'

jobs:
  compress_images:
    name: Compress Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compress
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
